# Generated by Django 4.2.11 on 2024-05-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_region_commune'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commune',
            new_name='Comuna',
        ),
    ]
