# Generated by Django 4.2.11 on 2024-05-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_rename_commune_comuna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comuna',
            new_name='Comunas',
        ),
    ]
