# Generated by Django 4.2.11 on 2024-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0008_alter_user_address_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
